version: "3.8"

services:
  video_clustering_engine:
    build: .
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G
    environment:
      - THRESH_CLUSTER_L1=${THRESH_CLUSTER_L1}
      - CROP_RATIO=${CROP_RATIO}
      - THRESH_COLOR_SVD=${THRESH_COLOR_SVD}
      - NUMBERS_COLOR_CLUSTER=${NUMBERS_COLOR_CLUSTER}
      - THRESH_TRIPLET_MODEL_L1=${THRESH_TRIPLET_MODEL_L1}
      - THRESH_TRIPLET_MODEL_L2=${THRESH_TRIPLET_MODEL_L2}
      - SKIP_FRAME=${SKIP_FRAME}
      - NUMBER_OF_WORKER=${NUMBER_OF_WORKER}
      - NUMBER_VIDEO_READERS=${NUMBER_VIDEO_READERS}
      - MAX_SVD_DIMENSION=${MAX_SVD_DIMENSION}
      - OUTPUT_FPS=${OUTPUT_FPS}
      - OUTPUT_VIDEO=${OUTPUT_VIDEO}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_DB_TOPIC=${KAFKA_DB_TOPIC}
      - BOOTSTRAP_SERVERS=${BOOTSTRAP_SERVERS}
      - OFFSET_RESET=${OFFSET_RESET}
      - GROUP_ID=${GROUP_ID}
      - LOG_FILE=${LOG_FILE}
      - MAIN_LOGGER_NAME=${MAIN_LOGGER_NAME}
      - PERF_LOG_FILE=${PERF_LOG_FILE}
      - PERFORMANCE_LOGGER_NAME=${PERFORMANCE_LOGGER_NAME}
      - FILE_SERVER_URL=${FILE_SERVER_URL}
      - FILE_SERVER_GET_URL=${FILE_SERVER_GET_URL}
      - WRITE_OUTPUT=${WRITE_OUTPUT}
      - IMAGE_HEIGHT=${IMAGE_HEIGHT}
    networks:
      - VideoClustering

networks:
  VideoClustering:
    external: true