version: "3.8"

services:
  video_clustering_api:
    build: .
    restart: always
    ports:
      - "20216:8080"
    environment:
      - SPRING_CONFIG_LOCATION=file:/config/application.properties
#      - SPRING_CONFIG_NAME=application.properties
    volumes:
      - ./config:/config
      - ./logs:/logs
    networks:
      - VideoClustering

networks:
  VideoClustering:
    external: true